namespace DI_2_Understanding_Lifetime.Services
{
    /// <summary>
    /// Implements IDateTime Interface
    /// </summary>
    public class DateTime : IDateTime
    {
        #region Private Members

        private readonly string _dateTime;

        #endregion

        #region Constructor

        /// <summary>
        /// Generates cuurent date time 
        /// </summary>
        public DateTime()
        {
            _dateTime = System.DateTime.Now.ToString();
        }

        #region Public Methods

        /// <summary>
        /// provodes generated dateTime
        /// </summary>
        /// <returns> dateTime generated by constructor  </returns>
        public string GetDate()
        {
            return _dateTime;
        }

        #endregion

    }
}
